DemoRealEstate/Models/Property.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DemoRealEstate.Models
{
    public class Property
    {
        public int Id { get; set; }

        [Required]
        [Display(Name ="Name of property")]
        public string PropertyName { get; set; }

        [Required]  
        [Display(Name = "Type of Property")]
        public string PropertyType { get; set; }

        [Required]
        public string Province { get; set; }

        [Required]
        [Display(Name = "City or Suburb")]
        public string CityorSuburb { get; set; }

        [Required]
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }

        [Required]
        [Display(Name = "Street")]
        public string Address { get; set; }

        [Display(Name = "Agent Name")]
        public string AgentName { get; set; }
        public string AgentId { get; set; }
        public double Price { get; set; }
        [Display(Name = "Agent Share R")]
        public int Agent_share { get; set; }
       
        [Display(Name = "Property details")]
        public string PropertyInf { get; set; }

        [Display(Name = "Agent Phone-number")]
        public string AgentPhoneNumber { get; set; }
        public bool Sold { get; set; }
        public Seller Seller { get; set; }
        public int Balance { get; set; }
        public int ClientId { get; set; }
        [Display(Name = "Select a seller")]
        public int SellerId { get; set; }
        [Url]
        public string ImageURL { get; set; }
        [Url]
        public string ImageURL1 { get; set; }
        [Url]
        public string ImageURL2 { get; set; }
        [Url]
        public string ImageURL3 { get; set; }
    }
}

DemoRealEstate/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoRealEstate.Models;
using Microsoft.AspNet.Identity;

namespace DemoRealEstate.Controllers
{
    [Authorize(Roles = "Agent")]
    public class AgentsController : Controller
    {
        private ApplicationDbContext _Context;

        public AgentsController()
        {
            _Context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _Context.Dispose();
        }

        // GET: Agents
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AgentProperty(string searchString, string province, string cityorsuburb)
        {

            var cityOrSuburb = new List<string>();

            var cities = from d in _Context.Properties
                         orderby d.CityorSuburb
                         select d.CityorSuburb;

            cityOrSuburb.AddRange(cities.Distinct());
            ViewBag.cityorsuburb = new SelectList(cityOrSuburb);

            var provinces = new List<string>();

            var provinceslist = from d in _Context.Properties
                                orderby d.Province
                                select d.Province;

            provinces.AddRange(provinceslist.Distinct());
            ViewBag.province = new SelectList(provinces);

            var loggedIn = User.Identity.GetUserId();

            var properties = _Context.Properties.Include(p => p.Seller);

            var AgentProperty = (from db in properties
                                where db.AgentId == loggedIn
                                select db);

            var Properties = AgentProperty;

            if (!String.IsNullOrEmpty(searchString))
            {
                Properties = Properties.Where(s => s.PropertyName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(province))
            {
                Properties = Properties.Where(x => x.Province == province);
            }

            if (!string.IsNullOrEmpty(cityorsuburb))
            {
                Properties = Properties.Where(x => x.CityorSuburb == cityorsuburb);
            }

            return View(Properties.ToList());
        }

        public ActionResult Edit(int? id)
        {

            var loggedIn = User.Identity.GetUserId();

            var Agent = _Context.Agents;

            var AgentId = (from db in Agent
                           where db.UserId == loggedIn
                           select db).SingleOrDefault();

            id = AgentId.Id;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = _Context.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,Email,PhoneNumber,UserId,Agent_share")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                agent.UserId = User.Identity.GetUserId();
                _Context.Entry(agent).State = EntityState.Modified;
                _Context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agent);
        }

        public ActionResult Details(int? id)
        {

            var loggedIn = User.Identity.GetUserId();

            var Agent = _Context.Agents;

            var AgentId = (from db in Agent
                           where db.UserId == loggedIn
                           select db).SingleOrDefault();

            id = AgentId.Id;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = _Context.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        public ActionResult MyClients()
        {
            return View();
        }
    }
}

DemoRealEstate/Controllers/SellersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoRealEstate.Models;
using Microsoft.AspNet.Identity;

namespace DemoRealEstate.Controllers
{
    [Authorize(Roles = "Agent, Admin")]
    public class SellersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Sellers
        public ActionResult Index(string searchString)
        {
            var sellers = from e in db.Seller
                          select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                sellers = sellers.Where(s => s.Name.Contains(searchString));
            }

            return View(sellers.ToList());
        }

        [Authorize(Roles = "Agent")]
        public ActionResult AgentSellers(string searchString)
        {

            var logged = User.Identity.GetUserId();

            var seller = from d in db.Seller
                         where d.AgentUserId == logged
                         select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                seller = seller.Where(s => s.Name.Contains(searchString));
            }

            return View(seller.ToList());
        }
        // GET: Sellers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Seller.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        [Authorize(Roles = "Agent")]
        // GET: Sellers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sellers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Agent")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,AgentUserId")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                seller.AgentUserId = User.Identity.GetUserId();
                db.Seller.Add(seller);
                db.SaveChanges();
                return RedirectToAction("Create", "Properties");
            }

            return View(seller);
        }

        // GET: Sellers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Seller.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        // POST: Sellers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seller).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seller);
        }

        // GET: Sellers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seller seller = db.Seller.Find(id);
            if (seller == null)
            {
                return HttpNotFound();
            }
            return View(seller);
        }

        // POST: Sellers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seller seller = db.Seller.Find(id);
            db.Seller.Remove(seller);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemoRealEstate/Views/Properties/Create.cshtml
@model DemoRealEstate.Models.Property

@{
    ViewBag.Title = "Create";
}


<div style="background-color:aliceblue; opacity:0.8; padding: 30px;">

    <h2>Step 2: Create Property</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PropertyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PropertyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PropertyType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PropertyType", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Province", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CityorSuburb, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CityorSuburb, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CityorSuburb, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PropertyInf, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PropertyInf, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyInf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SellerId, "SellerId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SellerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SellerId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyInf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyInf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyInf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageURL3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyInf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back", "Create", "Sellers")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

</div>

DemoRealEstate/Views/Properties/Delete.cshtml
@model DemoRealEstate.Models.Property

@{
    ViewBag.Title = "Delete";
}

<div style="background-color:aliceblue; padding: 30px;  opacity:0.8;">

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Property</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Seller.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Seller.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PropertyName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PropertyName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PropertyType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PropertyType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Province)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Province)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CityorSuburb)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CityorSuburb)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PostalCode)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AgentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AgentName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AgentId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AgentId)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PropertyInf)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PropertyInf)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sold)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sold)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "AgentProperty", "Agents")
            </div>
        }
    </div>

</div>

DemoRealEstate/Views/Properties/Details.cshtml
@model DemoRealEstate.Models.Property

@{
    ViewBag.Title = "Details";
}

<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" 
      />


<style>

    body {
        background-color: darkgray;
        background-image: none;
    }
    .Container {
        width: 100%;
        
    }
    .image{
        margin-top:50px;
        display:flex;
        align-items:center;
        justify-content:center;
    }
    .swiper{
        width:85%;
       
    }
    .swiper-slide{
        width:100%;
    }
    .Details{
        display: flex;
        font-size: 1.3em;
        text-transform: uppercase;
    }
    .address{
        margin-top: 90px;
    }

    .Button{
        margin-bottom: 15px;
    }

    .Button a{
        padding: 10px;
        background-color: aqua;
        color: black;
        font-weight: 600;
        border-radius: 5px;
    }
</style>

<div class="Container">
    <div class="image">
        @*<img src="@Html.Raw(Model.ImageURL)" alt="Alternate Text"  style="width:80%;" />*@
        <!-- Slider main container -->
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <div class="swiper-slide"><img src="@Html.Raw(Model.ImageURL)" alt="Alternate Text" style="width:100%;" /></div>
                <div class="swiper-slide"><img src="@Html.Raw(Model.ImageURL1)" alt="Alternate Text" style="width:100%;" /></div>
                <div class="swiper-slide"><img src="@Html.Raw(Model.ImageURL2)" alt="Alternate Text" style="width:100%;" /></div>
                <div class="swiper-slide"><img src="@Html.Raw(Model.ImageURL3)" alt="Alternate Text" style="width:100%;" /></div>
            </div>
            <!-- If we need pagination -->
            <div class="swiper-pagination"></div>

            <!-- If we need navigation buttons -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>

            <!-- If we need scrollbar -->
            <div class="swiper-scrollbar"></div>
        </div>
    </div>

    <div class="Details">
        <div>
            <h2>@Model.PropertyName @Model.PropertyType</h2>
            <hr />
            <dl>

                <dd>
                    @Html.DisplayFor(model => model.Seller.Name)
                </dd>

                <dd>
                    @Html.DisplayFor(model => model.PropertyName)
                </dd>

                <dd>
                    @Html.DisplayFor(model => model.PropertyType)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.AgentName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AgentName)
                </dd>

                <dd>
                    <p>R @Html.DisplayFor(model => model.Price)</p>
                </dd>

                <dd>
                    @Html.DisplayFor(model => model.PropertyInf)
                </dd>
                @{
                    if (User.IsInRole("Agent"))
                    {
                        <dt>
                            @Html.DisplayNameFor(model => model.Agent_share)
                        </dt>
                        <dd>
                            <p>R @Html.DisplayFor(model => model.Agent_share)</p>
                        </dd>
                    }
                }


            </dl>
        </div>
        <div class="address">
            <dl>
                <dd>
                    @Html.DisplayFor(model => model.Province)
                </dd>
                <dd>
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dd>
                    @Html.DisplayFor(model => model.CityorSuburb)
                </dd>
                <dd>
                    @Html.DisplayFor(model => model.PostalCode)
                </dd>
                <dd>
                    @Html.DisplayFor(model => model.AgentPhoneNumber)
                </dd>
            </dl>
        </div>
    </div>
    <hr/>

    @{
        var id = Model.Id;
        var client = ViewBag.Client;
        var clientId = ViewBag.ClientId;

        if (client == clientId && User.IsInRole("Client"))
        {
            <div class="Button">
                <a href="~/Payments/Create/@id">Make Payment</a>
            </div>
        }
    }

    @{
        if (User.IsInRole("Agent"))
        {
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id })  |
                @Html.ActionLink("Back to List", "AgentProperty", "Agents") |

            </p>
        }
        else
        {
            @Html.ActionLink("Back to List", "Index")
        }

    }

</div>



<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
<script>
    const swiper = new Swiper('.swiper', {
        // Optional parameters
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
            clickable: true
        },

        // Navigation arrows
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
</script>

DemoRealEstate/Views/Properties/Index.cshtml
@model IEnumerable<DemoRealEstate.Models.Property>

@{
    ViewBag.Title = "Index";
}

<style>
    body {
        background-color: rgb(128, 128, 128);
        background-image:none;
    }

    .filter-con {
        background-color: gainsboro;
        width: 80%;
        margin: auto;
        padding: 20px;
        margin-bottom: 25px;
        font-size: 1.2em;
        display: flex;
        text-transform:uppercase;
        margin-top:35px;
    }
    .filter-gr{
        display:inline-block;
        margin-right:20px;
    }
</style>
@{ 
    var returnhome = "";

    if (User.IsInRole("Admin"))
    {
        returnhome = "Admin/Index";
    }
}
<div class="filter-con">
    @using (Html.BeginForm())
    {
        <div class="filter-gr">
            <p>KeyWord: @Html.TextBox("SearchString")</p>
        </div>

        <div class="filter-gr">
            <p>
                Province: @Html.DropDownList("province", "All")
            </p>
        </div>

        <div class="filter-gr">
            <p>
                City or Suburb: @Html.DropDownList("cityorsuburb", "All")
            </p>
        </div><hr />
        <div class="filter-gr">
            <input type="submit" value="Filter" />
        </div>
        
        {
            if (User.IsInRole("Admin"))
            {
                    <a href="~/@returnhome">Back home</a>
            }
        }

    }
</div>

<style>
    .Container {
        width: 50%;
        margin: auto;
    }

    @@media(max-width: 800px) {
        .Container {
            width: 95%;
        }
    }

    .img img {
        width: 100%;
    }

    .inline-properties {
        display: inline-flex;
        background-color: darkgrey;
        width: 100%;
        margin-bottom: 10px;
    }

    .prop {
        margin: 5px;
        font-size: 1.1em;
        text-transform: uppercase;
    }
</style>

@foreach (var item in Model)
{
    <div class="Container">
        @{ 
            var id = item.Id;
        }
        <div class="img">
            <a href="~/Properties/Details/@id"><img src="@Html.Raw(item.ImageURL)" alt="Alternate Text" /></a>
        </div>
        <div class="inline-properties">
            <div class="prop">
                @Html.DisplayFor(modelItem => item.PropertyName)
            </div>
            <div class="prop">
                <p>R @Html.DisplayFor(modelItem => item.Price)</p>
            </div>
            <div class="prop">
                @Html.DisplayFor(modelItem => item.Province)
            </div>
            <div class="prop">
                @Html.DisplayFor(modelItem => item.CityorSuburb)
            </div>
            <div class="prop">
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </div>
        </div><hr/>
    </div>
}