DemoRealEstate/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DemoRealEstate.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [Phone]
        public string Phone_number { get; set; }
        public string User_Id { get; set; }
    }
}

DemoRealEstate/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoRealEstate.Models;
using Microsoft.AspNet.Identity;

namespace DemoRealEstate.Controllers
{
    public class ClientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.clients.ToList());
        }

        public ActionResult Me()
        {
            return View();
        }

        public ActionResult My_Property(string searchString)
        {
            var loggedIn = User.Identity.GetUserId();

            var client = (from d in db.clients
                        where d.User_Id == loggedIn
                        select d.Id).SingleOrDefault();

            var properties = db.Properties.Include(p => p.Seller);

            var AgentProperty = (from db in properties
                                 where db.ClientId == client
                                 select db);

            var Properties = AgentProperty;

            if (!String.IsNullOrEmpty(searchString))
            {
                Properties = Properties.Where(s => s.PropertyName.Contains(searchString));
            }

            return View(Properties.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Surname,Email,Phone_number,User_Id")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,Email,Phone_number,User_Id")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.clients.Find(id);
            db.clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemoRealEstate/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoRealEstate.Models;
using Microsoft.AspNet.Identity;

namespace DemoRealEstate.Controllers
{
    [Authorize(Roles = "Client")]
    public class PaymentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Payments
        public ActionResult Index()
        {
            var log = User.Identity.GetUserId();

            var client = (from d in db.clients
                          where d.User_Id == log
                          select d.Id).SingleOrDefault();

            var payments = db.Payments.Include(p => p.Client).Include(p => p.Property);

            payments = from d in payments
                       where d.ClientId == client
                       select d;

            return View(payments.ToList());
        }

        // GET: Payments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        public ActionResult Payment_done(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // GET: Payments/Create
        [Authorize(Roles = "Client")]
        public ActionResult Create(int? id)
        {
            double price = (from n in db.Properties
                         where n.Id == id
                         select n.Balance).SingleOrDefault();

            ViewBag.Price = price;

            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client")]
        public ActionResult Create(int? id, [Bind(Include = "Id,Price,Date,PropertyId,ClientId")] Payment payment)
        {

            double price = (from n in db.Properties
                            where n.Id == id
                            select n.Balance).SingleOrDefault();

            ViewBag.Price = price;

            if (ModelState.IsValid)
            {
                
                string userId = User.Identity.GetUserId();

                int Client_Id = (from c in db.clients
                                 where c.User_Id == userId
                                 select c.Id).SingleOrDefault();

                string Client_Name = (from c in db.clients
                                 where c.User_Id == userId
                                 select c.Name).SingleOrDefault();

                string Client_Email = (from c in db.clients
                                      where c.User_Id == userId
                                      select c.Email).SingleOrDefault();

                

                var Check_Buyer = (from c in db.Buyer
                               where c.PropertyId == (int)id
                               select c.AgentUserId).SingleOrDefault();

                string Agent_UserId = (from c in db.Properties
                                       where c.Id == id
                                       select c.AgentId).SingleOrDefault();

                if (Check_Buyer == null)
                {
                    var buyer = new Buyer
                    {
                        Name = Client_Name,
                        Email = Client_Email,
                        PropertyId = (int)id,
                        AgentUserId = Agent_UserId
                    };

                    db.Buyer.Add(buyer);
                    db.SaveChanges();
                }

                var PropName = (from d in db.Properties
                            where d.Id == id
                            select d.PropertyName).SingleOrDefault();

                var PropType = (from d in db.Properties
                                where d.Id == id
                                select d.PropertyType).SingleOrDefault();

                var Province = (from d in db.Properties
                                where d.Id == id
                                select d.Province).SingleOrDefault();

                var CityorSuburb = (from d in db.Properties
                                where d.Id == id
                                    select d.CityorSuburb).SingleOrDefault();

                var Postal = (from d in db.Properties
                                    where d.Id == id
                              select d.PostalCode).SingleOrDefault();

                var Address = (from d in db.Properties
                                    where d.Id == id
                               select d.Address).SingleOrDefault();

                var AgentName = (from d in db.Properties
                                    where d.Id == id
                                 select d.AgentName).SingleOrDefault();

                var AgentId = (from d in db.Properties
                                    where d.Id == id
                               select d.AgentId).SingleOrDefault();

                var Price = (from d in db.Properties
                                    where d.Id == id
                             select d.Price).SingleOrDefault();

                var Agent_share = (from d in db.Properties
                                    where d.Id == id
                                   select d.Agent_share).SingleOrDefault();

                var PropertyInf = (from d in db.Properties
                                    where d.Id == id
                                   select d.PropertyInf).SingleOrDefault();

                var Agent_phone = (from d in db.Properties
                                    where d.Id == id
                                   select d.AgentPhoneNumber).SingleOrDefault();

                var Balance = (from d in db.Properties
                                    where d.Id == id
                               select d.Balance).SingleOrDefault();

                Balance -= payment.Price;

                var Seller = (from d in db.Properties
                                    where d.Id == id
                              select d.SellerId).SingleOrDefault();

                var Image = (from d in db.Properties
                                    where d.Id == id
                             select d.ImageURL).SingleOrDefault();

                var Image1 = (from d in db.Properties
                                    where d.Id == id
                              select d.ImageURL1).SingleOrDefault();

                var Image2 = (from d in db.Properties
                                    where d.Id == id
                              select d.ImageURL2).SingleOrDefault();

                var Image3 = (from d in db.Properties
                                    where d.Id == id
                              select d.ImageURL3).SingleOrDefault();

                var propery = new Property
                {
                    Id = (int)id,
                    PropertyName = PropName,
                    PropertyType = PropType,
                    Province = Province,
                    CityorSuburb = CityorSuburb,
                    PostalCode = Postal,
                    Address = Address,
                    AgentName = AgentName,
                    AgentId = AgentId,
                    Price = Price,
                    Agent_share = Agent_share,
                    PropertyInf = PropertyInf,
                    AgentPhoneNumber = Agent_phone,
                    Sold = true,
                    ClientId = Client_Id,
                    Balance = Balance,
                    SellerId = Seller,
                    ImageURL = Image,
                    ImageURL1 = Image1,
                    ImageURL2 = Image2,
                    ImageURL3 = Image3
                };

                db.Entry(propery).State = EntityState.Modified;
                db.SaveChanges();

                var email = (from d in db.clients
                             where d.User_Id == userId
                             select d.Email).SingleOrDefault();

                var mail = new Email
                {
                    To = email,
                    Subject = "Payment Successful",
                    Body = "Payment of " + "R" + " " + payment.Price.ToString() + " Done"
                };

                mail.SendMail();

                payment.Date = DateTime.Now;
                payment.ClientId = Client_Id;
                payment.PropertyId = (int)id;
                db.Payments.Add(payment);
                db.SaveChanges();
                return RedirectToAction("Payment_done/" + payment.Id);
            }

            return View(payment);
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientId = new SelectList(db.clients, "Id", "Name", payment.ClientId);
            ViewBag.PropertyId = new SelectList(db.Properties, "Id", "PropertyName", payment.PropertyId);

DemoRealEstate/Views/Clients/Create.cshtml
@model DemoRealEstate.Models.Client

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoRealEstate/Views/Clients/Delete.cshtml
@model DemoRealEstate.Models.Client

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemoRealEstate/Views/Clients/Details.cshtml
@model DemoRealEstate.Models.Client

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DemoRealEstate/Views/Clients/Edit.cshtml
@model DemoRealEstate.Models.Client

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoRealEstate/Views/Clients/Index.cshtml
@model IEnumerable<DemoRealEstate.Models.Client>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User_Id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone_number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User_Id)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DemoRealEstate/Views/Clients/Me.cshtml
@{
    ViewBag.Title = "Me";
}
<style>
    .Container {
        width: 80%;
        text-align: center;
        background-color: aliceblue;
        opacity: 0.8;
        padding: 50px;
        margin: 30px 0;
        border-radius: 10px;
        margin: auto;
    }

    @@media(max-width: 800px) {
        .Container {
            width: 95%;
        }
    }
    .Header {
        padding: 50px;
        margin: auto;
        text-align: center;
        background-color: darkgrey;
        width: 100%;
    }

    .img img {
        width: 150px !important;
        margin: 25px;
    }

    .flex {
        display: flex;
        margin:auto;
        width: 40%;
        margin-top: 50px;
    }
    @@media(max-width: 800px){
        .flex{
            flex-direction:column;
            margin-top: 30px;
        }
    }
    .block {
        font-size: 1.3em;
        text-transform: uppercase;
    }
</style>
<div class="Container">
    <div class="Header">
        <h2>Welcome Client</h2>
    </div>
    <div class="flex">
        
        <div class="block">
            <div class="img">
                <img src="https://cdn-icons-png.flaticon.com/512/602/602175.png" alt="Alternate Text" />
            </div>
            <div>
                @Html.ActionLink("My Properties", "My_Property", "Clients")
            </div>
        </div>
        
        <div class="block">
            <div class="img">
                <img src="https://cdn-icons-png.flaticon.com/512/8818/8818279.png" />
            </div>
            <div>
                @Html.ActionLink("transaction", "Index", "Payments")
            </div>
        </div>
    </div>
</div>

DemoRealEstate/Views/Clients/My_Property.cshtml
@model IEnumerable<DemoRealEstate.Models.Property>

@{
    ViewBag.Title = "My_Property";
}

<style>

    .filter-con {
        background-color: gainsboro;
        width: 80%;
        margin: auto;
        padding: 10px 0px 0px 20px;
        margin-bottom: 20px;
        font-size: 1.2em;
        display: flex;
        text-transform: uppercase;
        margin-top: 35px;
        border-radius: 10px;
        opacity: 0.8;
    }

    .filter-gr {
        display: inline-block;
        margin-right: 10px;
    }
</style>


<div class="filter-con">
    @using (Html.BeginForm())
    {
        <div class="filter-gr">
            <p>@Html.TextBox("SearchString")</p>
        </div>
        <div class="filter-gr">
            <input type="submit" value="Search" />
        </div>
        <a href="~/Clients/Me">Back</a>
    }
</div>
<table class="table" style=" background-color:aliceblue; opacity:0.8;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PropertyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PropertyType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Province)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityorSuburb)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PropertyInf)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @{

                var Id = item.Id;
                var color = "green";

                if(item.Balance > 0)
                {
                    color = "red";
                }

            }
            <td>
                <img src="@Html.Raw(item.ImageURL)" alt="Alternate Text" style="width:150px;" />
            </td>
        
            <td>
                @Html.DisplayFor(modelItem => item.PropertyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PropertyType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CityorSuburb)
            </td>
            <td>
                <p>R @Html.DisplayFor(modelItem => item.Price)</p>
            </td>

            <td style="color: @color">
                <p>R @Html.DisplayFor(modelItem => item.Balance)</p>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PropertyInf)
            </td>
     
            <td>
                <a href="~/Properties/Details/@Id">Details</a>
            </td>
        </tr>
    }

</table>